use testdb;

CREATE TABLE IF NOT EXISTS `testdb`.`AnnualData` (
#  `idAnnualData` INT NOT NULL AUTO_INCREMENT,
  `index` VARCHAR(20) NULL,
  `Revenue USD Mil` VARCHAR(20) NULL,
  `Gross Margin percent` VARCHAR(20) NULL,
  `Operating Income USD Mil` VARCHAR(20) NULL,
  `Operating Margin percent` VARCHAR(20) NULL,
  `Net Income USD Mil` VARCHAR(20) NULL,
  `Earnings Per Share USD` VARCHAR(20) NULL,
  `Dividends USD` VARCHAR(20) NULL,
  `Payout Ratio percent` VARCHAR(20) NULL,
  `Shares Mil` VARCHAR(20) NULL,
  `Book Value Per Share USD` VARCHAR(20) NULL,
  `Operating Cash Flow USD Mil` VARCHAR(20) NULL,
  `Cap Spending USD Mil` VARCHAR(20) NULL,
  `Free Cash Flow USD Mil` VARCHAR(20) NULL,
  `Free Cash Flow Per Share USD` VARCHAR(20) NULL,
  `Working Capital USD Mil` VARCHAR(20) NULL,
  `Revenue` VARCHAR(20) NULL,
  `COGS` VARCHAR(20) NULL,
  `Gross Margin` VARCHAR(20) NULL,
  `SG&A` VARCHAR(20) NULL,
  `R&D` VARCHAR(20) NULL,
  `Other` VARCHAR(20) NULL,
  `Operating Margin` VARCHAR(20) NULL,
  `Net Int Inc & Other` VARCHAR(20) NULL,
  `EBT Margin` VARCHAR(20) NULL,
  `Tax Rate percent` VARCHAR(20) NULL,
  `Net Margin percent` VARCHAR(20) NULL,
  `Asset Turnover (Average)` VARCHAR(20) NULL,
  `Return on Assets percent` VARCHAR(20) NULL,
  `Financial Leverage (Average)` VARCHAR(20) NULL,
  `Return on Equity percent` VARCHAR(20) NULL,
  `Return on Invested Capital percent` VARCHAR(20) NULL,
  `Interest Coverage` VARCHAR(20) NULL,
  `Revenue YOY` VARCHAR(20) NULL,
  `Revenue 3yr avg` VARCHAR(20) NULL,
  `Revenue 5yr avg` VARCHAR(20) NULL,
  `Revenue 10yr avg` VARCHAR(20) NULL,
  `Operating income yoy` VARCHAR(20) NULL,
  `Operating income 3yr avg` VARCHAR(20) NULL,
  `Operating income 5yr avg` VARCHAR(20) NULL,
  `Operating income 10yr avg` VARCHAR(20) NULL,
  `Net income yoy` VARCHAR(20) NULL,
  `Net income 3yr avg` VARCHAR(20) NULL,
  `Net income 5yr avg` VARCHAR(20) NULL,
  `Net income 10yr avg` VARCHAR(20) NULL,
  `EPS YOY` VARCHAR(20) NULL,
  `EPS 3yr avg` VARCHAR(20) NULL,
  `EPS 5yr avg` VARCHAR(20) NULL,
  `EPS 10yr avg` VARCHAR(20) NULL,
  `Operating Cash Flow Growth percent YOY` VARCHAR(20) NULL,
  `Free Cash Flow Growth percent YOY` VARCHAR(20) NULL,
  `Cap Ex as a percent of Sales` VARCHAR(20) NULL,
  `Free Cash Flow/Sales percent` VARCHAR(20) NULL,
  `Free Cash Flow/Net Income` VARCHAR(20) NULL,
  `Cash & Short-Term Investments` VARCHAR(20) NULL,
  `Accounts Receivable` VARCHAR(20) NULL,
  `Inventory` VARCHAR(20) NULL,
  `Other Current Assets` VARCHAR(20) NULL,
  `Total Current Assets` VARCHAR(20) NULL,
  `Net PP&E` VARCHAR(20) NULL,
  `Intangibles` VARCHAR(20) NULL,
  `Other Long-Term Assets` VARCHAR(20) NULL,
  `Total Assets` VARCHAR(20) NULL,
  `Accounts Payable` VARCHAR(20) NULL,
  `Short-Term Debt` VARCHAR(20) NULL,
  `Taxes Payable` VARCHAR(20) NULL,
  `Accrued Liabilities` VARCHAR(20) NULL,
  `Other Short-Term Liabilities` VARCHAR(20) NULL,
  `Total Current Liabilities` VARCHAR(20) NULL,
  `Long-Term Debt` VARCHAR(20) NULL,
  `Other Long-Term Liabilities` VARCHAR(20) NULL,
  `Total Liabilities` VARCHAR(20) NULL,
  `Total Stockholders Equity` VARCHAR(20) NULL,
  `Total Liabilities & Equity` VARCHAR(20) NULL,
  `Current Ratio` VARCHAR(20) NULL,
  `Quick Ratio` VARCHAR(20) NULL,
  `Financial Leverage` VARCHAR(20) NULL,
  `Debt/Equity` VARCHAR(20) NULL,
  `Days Sales Outstanding` VARCHAR(20) NULL,
  `Days Inventory` VARCHAR(20) NULL,
  `Payables Period` VARCHAR(20) NULL,
  `Cash Conversion Cycle` VARCHAR(20) NULL,
  `Receivables Turnover` VARCHAR(20) NULL,
  `Inventory Turnover` VARCHAR(20) NULL,
  `Fixed Assets Turnover` VARCHAR(20) NULL,
  `Asset Turnover` VARCHAR(20) NULL,
  `SYMBOL` VARCHAR(20) NULL

#  PRIMARY KEY (`idAnnualData`)
)
ENGINE = InnoDB

#select * from AnnualData

#DROP TABLE IF EXISTS AnnualData
